✅ Rework checks against legacy node (#4269)

diff --git a/.github/workflows/build-status.yml b/.github/workflows/build-status.yml
--- a/.github/workflows/build-status.yml
+++ b/.github/workflows/build-status.yml
@@ -330,6 +330,26 @@ jobs:
         run: yarn workspaces foreach -pvi --no-private exec "git restore -s@ -SW -- test-bundle || true"
       - name: Check bundles
         run: yarn workspaces foreach -pvi --no-private run test-bundle
+      - name: Check legacy bundles
+        run: |
+          export NODE_VERSION="$(node --version)"
+          export NVS_HOME="$HOME/.nvs"
+          git clone --branch v1.7.1 --depth 1 https://github.com/jasongin/nvs "$NVS_HOME"
+          if [ "$(git -C "$NVS_HOME" rev-parse HEAD)" != "b87ae9593cd20e7b667e9099240c9befeb50659f" ]; then
+              echo "ERROR: HEAD is not the expected commit hash"
+              exit 1
+          fi
+          chmod +x "$NVS_HOME/nvs"
+          export PATH="$PATH:$NVS_HOME"
+          if [ "$(node --version)" != "$NODE_VERSION" ]; then
+              echo "ERROR: Node version got updated from $NODE_VERSION to $(node --version)"
+              exit 2
+          fi
+          yarn workspaces foreach -pvi --no-private run test-legacy-bundle
+          if [ "$(node --version)" != "$NODE_VERSION" ]; then
+              echo "ERROR: Node version got updated from $NODE_VERSION to $(node --version)"
+              exit 3
+          fi
       - name: Check publication lint
         run: yarn publint:all
   test_types:
@@ -388,48 +408,6 @@ jobs:
         run: |
           yarn workspaces foreach -pvi --no-private exec "sed -i 's/fc-expect-error-require-exactOptionalPropertyTypes/ts-expect-error/g' test-types/*.mts"
           yarn workspaces foreach -pvi --no-private exec "cd test-types && yarn dlx -p typescript tsc --noEmit --skipLibCheck --strict --exactOptionalPropertyTypes *.mts"
-  test_node_8:
-    name: 'Test legacy Node'
-    needs:
-      - warmup_yarn_cache
-      - production_packages
-    runs-on: ubuntu-latest
-    steps:
-      - uses: actions/checkout@8ade135a41bc03ea155e62e844d188df1ea18608 # v4.1.0
-      - name: Using Node v18.x
-        uses: actions/setup-node@5e21ff4d9bc1a8cf6de233a3057d20ec6b3fb69d # v3.8.1
-        with:
-          node-version: '18.x'
-          cache: 'yarn'
-          check-latest: true
-      - name: Install dependencies
-        run: yarn install --immutable
-      - name: Download production packages
-        uses: actions/download-artifact@9bc31d5ccc31df68ecc42ccf4149144866c47d8a # v3.0.2
-        with:
-          name: bundles
-          path: packages/
-      - name: Unpack production packages
-        run: yarn unpack:all
-      - name: Alter internals to behave as if published
-        run: yarn workspaces foreach -pRvi --from '@fast-check/test-minimal-support' --no-private exec yarn node $(yarn bin packaged) --keep-node-modules
-      - name: Using Node v8.x
-        uses: actions/setup-node@5e21ff4d9bc1a8cf6de233a3057d20ec6b3fb69d # v3.8.1
-        with:
-          node-version: '8.x'
-          check-latest: true
-      - name: Test packages/test-minimal-support/
-        run: |
-          cd packages/test-minimal-support
-          node --version
-          node main.js
-      # Re-install node 16, for clean-up related logic as it does not work with node 8
-      # The caching logic of actions/setup-node calls yarn to know the version
-      - name: Using Node v18.x
-        uses: actions/setup-node@5e21ff4d9bc1a8cf6de233a3057d20ec6b3fb69d # v3.8.1
-        with:
-          node-version: '18.x'
-          check-latest: true
 
   # Publication jobs
   publish_documentation:
@@ -457,7 +435,6 @@ jobs:
       - typecheck
       - test
       - test_bundle
-      - test_node_8
       - test_types
     if: github.event_name == 'push'
     runs-on: ubuntu-latest
