💚 Attempt to patch untar step (#4384)
Third attempt, another philosophy now.

diff --git a/.github/workflows/build-status.yml b/.github/workflows/build-status.yml
--- a/.github/workflows/build-status.yml
+++ b/.github/workflows/build-status.yml
@@ -263,7 +263,12 @@ jobs:
           name: bundles
           path: packages/
       - name: Unpack production packages
+        if: matrix.os != 'windows-latest'
         run: yarn unpack:all
+      - name: Unpack production packages (Windows only)
+        if: matrix.os == 'windows-latest'
+        # untar seems to fail on Windows when untaring already existing files
+        run: yarn unpack:all || true
       - name: Alter internals to behave as if published
         run: yarn workspaces foreach -pRvi --from '${{matrix.package-name}}' --no-private --exclude '${{matrix.package-name}}' exec yarn node $(yarn bin packaged) --keep-node-modules
       - name: Unit tests
